name: Auto Release

on:
  push:
    branches:
      - main # Скрипт спрацьовує при кожному пуші в гілку main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Тут йдуть ваші кроки для збірки (build) програми, наприклад:
      # - name: Setup Node.js
      #   uses: actions/setup-node@v4
      # - name: Install dependencies
      #   run: npm install
      # - name: Build exe
      #   run: npm run build

      - name: Оновлення Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: false
          title: "Оновлена версія"
          files: |
            ./LSPD_Binder.exe # Вкажіть шлях до вашого exe файлу у проєкті
